[package]
name = "grab"
version = "1.0.0"
authors = ["Abu Sakib <mabusakib@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
clap = "3"
colored = "2"